### ISSUE TITLE
dataset label(U, T, F) Meaning 

### ISSUE THREAD

**Issue by byew** [MickeysClubhouse/COVID-19-rumor-dataset#1]
Hello, I found 3 labels (F, T, U)    in the data set. I want to know what they mean.

I guessed, **F** is no rumor, **T** is rumor, **U** is not sure whether it is a rumor

Thank you very much for your answers

**Comment by MickeysClubhouse** [comment]
Hi, F means the rumor is fake (which means the news/tweet is not real);  T means the rumor is truth;  U is not sure.

Thanks
